export const PROTOCOL_VERSION = 3;

export const Methods = {
  CONNECT: "connect",
  HEALTH: "health",
  STATUS: "status",

  AGENT: "agent",
  AGENT_WAIT: "agent.wait",
  AGENT_IDENTITY_GET: "agent.identity.get",

  CHAT_SEND: "chat.send",
  CHAT_HISTORY: "chat.history",
  CHAT_ABORT: "chat.abort",
  CHAT_INJECT: "chat.inject",
  CHAT_SESSION_STATUS: "chat.session.status",

  AGENTS_LIST: "agents.list",
  AGENTS_CREATE: "agents.create",
  AGENTS_UPDATE: "agents.update",
  AGENTS_DELETE: "agents.delete",
  AGENTS_FILES_LIST: "agents.files.list",
  AGENTS_FILES_GET: "agents.files.get",
  AGENTS_FILES_SET: "agents.files.set",
  AGENTS_LINKS_LIST: "agents.links.list",
  AGENTS_LINKS_CREATE: "agents.links.create",
  AGENTS_LINKS_UPDATE: "agents.links.update",
  AGENTS_LINKS_DELETE: "agents.links.delete",

  CONFIG_GET: "config.get",
  CONFIG_APPLY: "config.apply",
  CONFIG_PATCH: "config.patch",
  CONFIG_SCHEMA: "config.schema",
  CONFIG_DEFAULTS: "config.defaults",
  CONFIG_PERMISSIONS_LIST: "config.permissions.list",
  CONFIG_PERMISSIONS_GRANT: "config.permissions.grant",
  CONFIG_PERMISSIONS_REVOKE: "config.permissions.revoke",

  SESSIONS_LIST: "sessions.list",
  SESSIONS_PREVIEW: "sessions.preview",
  SESSIONS_PATCH: "sessions.patch",
  SESSIONS_DELETE: "sessions.delete",
  SESSIONS_RESET: "sessions.reset",

  SKILLS_LIST: "skills.list",
  SKILLS_GET: "skills.get",
  SKILLS_UPDATE: "skills.update",

  CRON_LIST: "cron.list",
  CRON_CREATE: "cron.create",
  CRON_UPDATE: "cron.update",
  CRON_DELETE: "cron.delete",
  CRON_TOGGLE: "cron.toggle",
  CRON_STATUS: "cron.status",
  CRON_RUN: "cron.run",
  CRON_RUNS: "cron.runs",

  CHANNELS_LIST: "channels.list",
  CHANNELS_STATUS: "channels.status",
  CHANNELS_TOGGLE: "channels.toggle",
  CHANNEL_INSTANCES_LIST: "channels.instances.list",
  CHANNEL_INSTANCES_CREATE: "channels.instances.create",
  CHANNEL_INSTANCES_UPDATE: "channels.instances.update",
  CHANNEL_INSTANCES_DELETE: "channels.instances.delete",

  APPROVALS_LIST: "exec.approval.list",
  APPROVALS_APPROVE: "exec.approval.approve",
  APPROVALS_DENY: "exec.approval.deny",

  USAGE_GET: "usage.get",
  USAGE_SUMMARY: "usage.summary",
  QUOTA_USAGE: "quota.usage",

  LOGS_TAIL: "logs.tail",

  TEAMS_LIST: "teams.list",
  TEAMS_CREATE: "teams.create",
  TEAMS_GET: "teams.get",
  TEAMS_DELETE: "teams.delete",
  TEAMS_UPDATE: "teams.update",
  TEAMS_TASK_LIST: "teams.tasks.list",
  TEAMS_TASK_GET: "teams.tasks.get",
  TEAMS_TASK_CREATE: "teams.tasks.create",
  TEAMS_TASK_APPROVE: "teams.tasks.approve",
  TEAMS_TASK_REJECT: "teams.tasks.reject",
  TEAMS_TASK_ASSIGN: "teams.tasks.assign",
  TEAMS_MEMBERS_ADD: "teams.members.add",
  TEAMS_MEMBERS_REMOVE: "teams.members.remove",

  HEARTBEAT_GET: "heartbeat.get",
  HEARTBEAT_SET: "heartbeat.set",
  HEARTBEAT_TOGGLE: "heartbeat.toggle",
  HEARTBEAT_LOGS: "heartbeat.logs",

  TENANTS_MINE: "tenants.mine",
  TENANTS_LIST: "tenants.list",
  TENANTS_GET: "tenants.get",
  TENANTS_CREATE: "tenants.create",
  TENANTS_UPDATE: "tenants.update",
  TENANTS_USERS_LIST: "tenants.users.list",

  SEND: "send",

  MODELS_LIST: "models.list",

  DEVICE_PAIR_LIST: "device.pair.list",
  DEVICE_PAIR_APPROVE: "device.pair.approve",
  DEVICE_PAIR_DENY: "device.pair.deny",
  DEVICE_PAIR_REVOKE: "device.pair.revoke",

  WHATSAPP_QR_START: "whatsapp.qr.start",
  ZALO_PERSONAL_QR_START: "zalo.personal.qr.start",
  ZALO_PERSONAL_CONTACTS: "zalo.personal.contacts",
} as const;

export const Events = {
  AGENT: "agent",
  CHAT: "chat",
  HEALTH: "health",
  CRON: "cron",
  EXEC_APPROVAL_REQUESTED: "exec.approval.requested",
  EXEC_APPROVAL_RESOLVED: "exec.approval.resolved",
  PRESENCE: "presence",
  TICK: "tick",
  SHUTDOWN: "shutdown",
  SESSION_UPDATED: "session.updated",
  TRACE_UPDATED: "trace.updated",
  TRACE_STATUS: "trace.status",
  SKILL_DEPS_CHECKED: "skill.deps.checked",
  SKILL_DEPS_COMPLETE: "skill.deps.complete",
  SKILL_DEPS_INSTALLING: "skill.deps.installing",
  SKILL_DEPS_INSTALLED: "skill.deps.installed",
  DEVICE_PAIR_REQUESTED: "device.pair.requested",
  DEVICE_PAIR_RESOLVED: "device.pair.resolved",
  HEARTBEAT: "heartbeat",
  LOG: "log",
  TEAM_TASK_CREATED: "team.task.created",
  TEAM_TASK_COMPLETED: "team.task.completed",
  TEAM_TASK_FAILED: "team.task.failed",
  TEAM_TASK_APPROVED: "team.task.approved",
  TEAM_TASK_REJECTED: "team.task.rejected",
  TEAM_TASK_PROGRESS: "team.task.progress",
  TEAM_MESSAGE_SENT: "team.message.sent",
  AGENT_LINK_CREATED: "agent_link.created",
  AGENT_LINK_UPDATED: "agent_link.updated",
  AGENT_LINK_DELETED: "agent_link.deleted",
  WHATSAPP_QR_CODE: "whatsapp.qr.code",
  WHATSAPP_QR_DONE: "whatsapp.qr.done",
  ZALO_PERSONAL_QR_CODE: "zalo.personal.qr.code",
  ZALO_PERSONAL_QR_DONE: "zalo.personal.qr.done",
} as const;

export const AgentEventTypes = {
  RUN_STARTED: "run.started",
  RUN_COMPLETED: "run.completed",
  RUN_FAILED: "run.failed",
  RUN_CANCELLED: "run.cancelled",
  TOOL_CALL: "tool.call",
  TOOL_RESULT: "tool.result",
  BLOCK_REPLY: "block.reply",
} as const;

export const ChatEventTypes = {
  CHUNK: "chunk",
  MESSAGE: "message",
  THINKING: "thinking",
} as const;
